import { z } from 'zod'
import fs from 'node:fs'
import path from 'node:path'
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { APP_ROOT } from '../adonis.js'
import { text } from '../reply.js'

const VIEWS = new URL('resources/views/', APP_ROOT)

/**
 * Turns `components/ui/card.edge` into the tag an author writes: `@ui.card`.
 * Edge camelCases each path segment, which is the single most common thing
 * agents get wrong in this project.
 */
function tagNameFor(relativePath: string) {
  return relativePath
    .replace(/\.edge$/, '')
    .split('/')
    .map((segment) => segment.replace(/[_-](\w)/g, (_m, char) => char.toUpperCase()))
    .join('.')
}

/** Pulls the leading `{{-- ... --}}` doc comment out of a component. */
function docCommentOf(source: string) {
  const match = source.match(/^\s*\{\{--([\s\S]*?)--\}\}/)
  if (!match) return null
  return match[1]
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .join('\n')
}

export function registerProjectTools(server: McpServer) {
  server.registerTool(
    'list_components',
    {
      title: 'List Edge components',
      description:
        'Every Edge component with the exact tag name to call it by and its documented props. Use this before writing a template — component tag names are camelCased from the file path, so guessing them silently renders literal text instead of erroring.',
      inputSchema: {
        name: z.string().optional().describe('Substring filter on the tag name'),
        withDocs: z
          .boolean()
          .optional()
          .describe('Include the full prop documentation (default true)'),
      },
    },
    async ({ name, withDocs }) => {
      const root = new URL('components/', VIEWS)
      if (!fs.existsSync(root)) return text({ total: 0, components: [] })

      const components = []
      for (const entry of fs.readdirSync(root, { withFileTypes: true, recursive: true })) {
        if (!entry.isFile() || !entry.name.endsWith('.edge')) continue

        const abs = path.join(entry.parentPath, entry.name)
        const relative = path.relative(root.pathname, abs)
        const tag = tagNameFor(relative)

        if (name && !tag.toLowerCase().includes(name.toLowerCase())) continue

        const source = fs.readFileSync(abs, 'utf8')
        components.push({
          tag: `@${tag}`,
          selfClosing: `@!${tag}({ ... })`,
          file: `resources/views/components/${relative}`,
          hasSlots: /\$slots\./.test(source),
          docs: withDocs === false ? undefined : docCommentOf(source),
        })
      }

      return text({
        total: components.length,
        note: 'Call with children as `@tag({...}) ... @end`, or self-closing as `@!tag({...})`.',
        components: components.sort((a, b) => a.tag.localeCompare(b.tag)),
      })
    }
  )

  server.registerTool(
    'list_views',
    {
      title: 'List page templates',
      description: 'Page and partial templates with the view name you pass to `view.render()`.',
      inputSchema: {
        includeShowcase: z
          .boolean()
          .optional()
          .describe('Include the 98 generated Imtaqin reference pages (default false)'),
      },
    },
    async ({ includeShowcase }) => {
      const views = []
      for (const group of ['pages', 'partials']) {
        const root = new URL(`${group}/`, VIEWS)
        if (!fs.existsSync(root)) continue

        for (const entry of fs.readdirSync(root, { withFileTypes: true, recursive: true })) {
          if (!entry.isFile() || !entry.name.endsWith('.edge')) continue
          const relative = path.relative(VIEWS.pathname, path.join(entry.parentPath, entry.name))
          if (!includeShowcase && relative.includes('pages/showcase/')) continue
          views.push(relative.replace(/\.edge$/, ''))
        }
      }

      return text({
        total: views.length,
        hint: "view.render('pages/users/index')",
        views: views.sort(),
      })
    }
  )

  server.registerTool(
    'project_conventions',
    {
      title: 'Project conventions',
      description:
        'The navigation config, permission catalogue and the non-obvious framework rules, in one call. Read this before adding a page, permission or nav entry.',
      inputSchema: {},
    },
    async () => {
      const read = (relative: string) => {
        const target = new URL(relative, APP_ROOT)
        return fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null
      }

      const permissions = read('config/permissions.ts')
      const slugs = permissions
        ? [...permissions.matchAll(/slug:\s*'([^']+)'/g)].map((m) => m[1])
        : []

      return text({
        gotchas: [
          'database/schema.ts is GENERATED by `node ace migration:run` — never edit it. Models extend the generated classes.',
          'Edge camelCases component tag names from the file path. A wrong name renders as literal text, it does not error. Use list_components.',
          'Block tags (@if/@each) cannot appear inline inside an HTML tag; use ternary interpolation for conditional attributes.',
          '@each needs a bare identifier — hoist `x || []` into an @let first.',
          'This app uses GET and POST only. No PUT/PATCH/DELETE.',
        ],
        singleSourcesOfTruth: {
          navigation: 'config/menu.ts',
          permissions: 'config/permissions.ts',
          branding: 'config/dashboard.ts',
        },
        permissionSlugs: slugs,
        addAPage: [
          'app/controllers/<Domain>/<Action>/index.ts  (show() renders, handle() acts)',
          'start/routes/<domain>.ts  (named route + auth + permission middleware)',
          'resources/views/pages/<domain>/<action>.edge  (wrap in @layouts.dashboard)',
          'config/menu.ts  (nav entry)',
        ],
        referenceImplementation: 'app/controllers/User/ — copy this shape for a new resource.',
        fullGuide: 'AGENTS.md',
      })
    }
  )
}
