import { z } from 'zod'
import fs from 'node:fs'
import path from 'node:path'
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { APP_ROOT } from '../adonis.js'
import { text } from '../reply.js'

const VIEWS = new URL('resources/views/', APP_ROOT)

/**
 * Turns `components/ui/card.edge` into the tag an author writes: `@ui.card`.
 * Edge camelCases each path segment, which is the single most common thing
 * agents get wrong in this project.
 */
function tagNameFor(relativePath: string) {
  return relativePath
    .replace(/\.edge$/, '')
    .split('/')
    .map((segment) => segment.replace(/[_-](\w)/g, (_m, char) => char.toUpperCase()))
    .join('.')
}

/** Pulls the leading `{{-- ... --}}` doc comment out of a component. */
function docCommentOf(source: string) {
  const match = source.match(/^\s*\{\{--([\s\S]*?)--\}\}/)
  if (!match) return null
  return match[1]
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .join('\n')
}

export function registerProjectTools(server: McpServer) {
  server.registerTool(
    'list_components',
    {
      title: 'List Edge components',
      description:
        'Every Edge component with the exact tag name to call it by and its documented props. Use this before writing a template — component tag names are camelCased from the file path, so guessing them silently renders literal text instead of erroring.',
      inputSchema: {
        name: z.string().optional().describe('Substring filter on the tag name'),
        withDocs: z
          .boolean()
          .optional()
          .describe('Include the full prop documentation (default true)'),
      },
    },
    async ({ name, withDocs }) => {
      const root = new URL('components/', VIEWS)
      if (!fs.existsSync(root)) return text({ total: 0, components: [] })

      const components = []
      for (const entry of fs.readdirSync(root, { withFileTypes: true, recursive: true })) {
        if (!entry.isFile() || !entry.name.endsWith('.edge')) continue

        const abs = path.join(entry.parentPath, entry.name)
        const relative = path.relative(root.pathname, abs)
        const tag = tagNameFor(relative)

        if (name && !tag.toLowerCase().includes(name.toLowerCase())) continue

        const source = fs.readFileSync(abs, 'utf8')
        components.push({
          tag: `@${tag}`,
          selfClosing: `@!${tag}({ ... })`,
          file: `resources/views/components/${relative}`,
          hasSlots: /\$slots\./.test(source),
          docs: withDocs === false ? undefined : docCommentOf(source),
        })
      }

      return text({
        total: components.length,
        note: 'Call with children as `@tag({...}) ... @end`, or self-closing as `@!tag({...})`.',
        components: components.sort((a, b) => a.tag.localeCompare(b.tag)),
      })
    }
  )

  server.registerTool(
    'list_views',
    {
      title: 'List page templates',
      description: 'Page and partial templates with the view name you pass to `view.render()`.',
      inputSchema: {
        includeShowcase: z
          .boolean()
          .optional()
          .describe('Include the 98 generated Imtaqin reference pages (default false)'),
      },
    },
    async ({ includeShowcase }) => {
      const views = []
      for (const group of ['pages', 'partials']) {
        const root = new URL(`${group}/`, VIEWS)
        if (!fs.existsSync(root)) continue

        for (const entry of fs.readdirSync(root, { withFileTypes: true, recursive: true })) {
          if (!entry.isFile() || !entry.name.endsWith('.edge')) continue
          const relative = path.relative(VIEWS.pathname, path.join(entry.parentPath, entry.name))
          if (!includeShowcase && relative.includes('pages/showcase/')) continue
          views.push(relative.replace(/\.edge$/, ''))
        }
      }

      return text({
        total: views.length,
        hint: "view.render('pages/users/index')",
        views: views.sort(),
      })
    }
  )

  server.registerTool(
    'project_conventions',
    {
      title: 'Project conventions',
      description:
        'The navigation config, permission catalogue and the non-obvious framework rules, in one call. Read this before adding a page, permission or nav entry.',
      inputSchema: {},
    },
    async () => {
      const read = (relative: string) => {
        const target = new URL(relative, APP_ROOT)
        return fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null
      }

      const permissions = read('config/permissions.ts')
      const slugs = permissions
        ? [...permissions.matchAll(/slug:\s*'([^']+)'/g)].map((m) => m[1])
        : []

      return text({
        gotchas: [
          'database/schema.ts is GENERATED by `node ace migration:run` — never edit it. Models extend the generated classes.',
          'Edge camelCases component tag names from the file path. A wrong name renders as literal text, it does not error. Use list_components.',
          'Block tags (@if/@each) cannot appear inline inside an HTML tag; use ternary interpolation for conditional attributes.',
          '@each needs a bare identifier — hoist `x || []` into an @let first.',
          'This app uses GET and POST only. No PUT/PATCH/DELETE.',
        ],
        singleSourcesOfTruth: {
          navigation: 'config/menu.ts',
          permissions: 'config/permissions.ts',
          branding: 'config/dashboard.ts',
        },
        permissionSlugs: slugs,
        workingFromADocumentFolder: {
          when: 'You are pointed at a directory of specs, notes or markdown -- "implement what is in docs/spec/".',
          risk: 'Reading twenty files fills your context, the original task falls out of it, and you finish something adjacent to what was asked. Context is not durable; the ledger below is.',
          protocol: [
            '1. Index first: list the folder, read only titles and headings, build a one-line-per-file map. Never bulk-read the directory into context.',
            '2. Before writing code, memory_write a note of kind "todo" holding: the task in one sentence in the requester words, the source folder and files in scope, a checklist of [ ] / [x] / [skip: why], and an Open questions list.',
            '3. Work one checklist item at a time. Read that item file when you reach it, implement, verify, then memory_write the ledger with the box ticked. Reuse the same slug so it stays one note.',
            '4. Reconcile, do not transcribe. Where a document contradicts project_conventions or AGENTS.md, this repo wins -- record the conflict under Open questions and say so in your reply.',
            '5. Never silently narrow scope. If the folder is larger than what you can finish, say what you left out. A [skip: ...] line is honest; a checklist quietly missing files is not.',
            '6. Finish with a changeset, then memory_delete the ledger. A stale todo note read as live work by the next agent is worse than no note.',
          ],
          recovery:
            'If you were interrupted or compacted, memory_list recovers the whole task -- look for a note of kind "todo" before assuming you are starting fresh.',
        },
        readDocsFirst: {
          rule: 'Before writing code against any framework API, look it up with the adonis-docs MCP server (detect_version, search_docs, get_doc). Do not write framework code from memory.',
          why: 'AdonisJS v7 alpha, Lucid 22, Edge 6 and VineJS all moved recently, and a wrong API here fails silently rather than raising: a mistyped Edge tag renders as literal text, a wrong Lucid decorator just never loads the relation.',
          mandatoryFor: {
            'models, relations, queries, migrations': 'Lucid docs',
            'Edge templates, components, slots': 'Edge docs',
            'validators': 'VineJS docs',
            'routes, middleware, exceptions': 'AdonisJS core HTTP docs',
            'auth, session, shield, limiter': 'that package docs',
          },
          precedence:
            'Docs describe the framework; project_conventions and AGENTS.md describe deliberate deviations in THIS app. Where they disagree, this project wins -- say so rather than silently following the docs.',
          pairWith:
            'search_docs proves the API exists; list_components, database_schema and list_routes tell you what this codebase named it. Use both.',
          ifUnconfirmed:
            'If you could not confirm an API in the docs, say so in your reply instead of shipping a guess.',
        },
        changesets: {
          rule: 'Every task ships a changeset. Run `npm run changeset` before reporting work done -- it belongs next to `npm run typecheck` in the definition of done, not reserved for significant changes.',
          verify:
            'npm run changeset:check -- fails when the diff against main has no note describing it.',
          why: 'Private single package, nothing is published. The note exists so the next agent learns what changed and why without archaeology through commits. Do not run `changeset publish`.',
          bump: {
            major:
              'a rule changed such that existing code is now wrong -- must end with a Migrating: paragraph',
            minor: 'new capability: a component, MCP tool, middleware, convention',
            patch: 'a fix, clarification, or doc edit that breaks nothing',
          },
          exempt: 'Lockfile-only changes and edits inside .changeset/ itself. Nothing else.',
        },
        controllerLayout: {
          path: 'app/controllers/<Domain>/<Action>/index.ts',
          rule: 'Always three segments. A domain with a single screen still gets an action folder named Index (Profile/Index/index.ts) -- never Profile/index.ts.',
          domain: 'PascalCase, singular: User, Role, AuditLog, OrgUnit.',
          actions: {
            List: 'index/table screen -- handle()',
            Create: 'GET create form + POST create -- show(), handle()',
            Update: 'GET :id/edit form + POST :id/edit -- show(), handle()',
            Delete: 'POST :id/delete -- handle()',
            Show: 'read-only detail screen -- handle()',
            Index: 'a domain that is one screen -- handle()',
          },
          note: 'The route is named users.edit but the controller folder is User/Update -- named after the mutation, not the URL.',
          api: 'JSON controllers mirror the same shape under an Api/ prefix: app/controllers/Api/<Domain>/<Action>/index.ts. Nothing else is allowed at the top level.',
          barrel:
            'Path maps to #generated/controllers: User/Update/index.ts -> controllers.user.update.Index, Api/Auth/Login/index.ts -> controllers.api.auth.login.Index.',
        },
        addAPage: [
          'app/controllers/<Domain>/<Action>/index.ts  (show() renders, handle() acts)',
          'start/routes/<domain>.ts  (named route + auth + permission middleware)',
          'resources/views/pages/<domain>/<action>.edge  (wrap in @layouts.dashboard)',
          'config/menu.ts  (nav entry)',
        ],
        referenceImplementation: 'app/controllers/User/ — copy this shape for a new resource.',
        fullGuide: 'AGENTS.md',
      })
    }
  )
}
