/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auditLog: {
    list: {
      Index: () => import('#controllers/AuditLog/List/index'),
    },
  },
  auth: {
    login: {
      Index: () => import('#controllers/Auth/Login/index'),
    },
    logout: {
      Index: () => import('#controllers/Auth/Logout/index'),
    },
    register: {
      Index: () => import('#controllers/Auth/Register/index'),
    },
  },
  dashboard: {
    Index: () => import('#controllers/Dashboard/index'),
  },
  icon: {
    list: {
      Index: () => import('#controllers/Icon/List/index'),
    },
  },
  role: {
    create: {
      Index: () => import('#controllers/Role/Create/index'),
    },
    delete: {
      Index: () => import('#controllers/Role/Delete/index'),
    },
    list: {
      Index: () => import('#controllers/Role/List/index'),
    },
    update: {
      Index: () => import('#controllers/Role/Update/index'),
    },
  },
  showcase: {
    Index: () => import('#controllers/Showcase/index'),
  },
  user: {
    create: {
      Index: () => import('#controllers/User/Create/index'),
    },
    delete: {
      Index: () => import('#controllers/User/Delete/index'),
    },
    list: {
      Index: () => import('#controllers/User/List/index'),
    },
    update: {
      Index: () => import('#controllers/User/Update/index'),
    },
  },
}
