/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditLogSchema extends BaseModel {
  static $columns = ['auditableId', 'auditableType', 'createdAt', 'event', 'id', 'ipAddress', 'newValues', 'oldValues', 'summary', 'userAgent', 'userId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare auditableId: number | null
  @column()
  declare auditableType: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare event: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare newValues: any | null
  @column()
  declare oldValues: any | null
  @column()
  declare summary: string | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number | null
}

export class PermissionRoleSchema extends BaseModel {
  static $columns = ['id', 'permissionId', 'roleId'] as const
  $columns = PermissionRoleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare permissionId: number
  @column()
  declare roleId: number
}

export class PermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'group', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare group: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RoleUserSchema extends BaseModel {
  static $columns = ['id', 'roleId', 'userId'] as const
  $columns = RoleUserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roleId: number
  @column()
  declare userId: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isSystem', 'name', 'slug', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'email', 'fullName', 'id', 'isActive', 'lastLoginAt', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
