/*
|--------------------------------------------------------------------------
| Showcase pages (GENERATED)
|--------------------------------------------------------------------------
|
| Written by scripts/convert-showcase-pages.mjs. Do not edit by hand.
|
| These are the Imtaqin template pages rendered as reference markup at
| /showcase/:page. They are not application screens -- copy the markup you
| need into a real page rather than building on top of them.
|
*/

export const showcasePages = [
  'accordions-collpase',
  'add-products',
  'alerts',
  'apex-charts',
  'avatars',
  'badge',
  'blog-create',
  'blog-details',
  'blog',
  'borders',
  'breadcrumb',
  'breakpoints',
  'buttongroup',
  'buttons',
  'cards',
  'carousel',
  'cart',
  'chartjs-charts',
  'chat',
  'checkout',
  'colors',
  'columns',
  'contacts',
  'css-grid',
  'data-tables',
  'draggable-cards',
  'dropdowns',
  'echarts',
  'edit-products',
  'empty',
  'faqs',
  'file-manager',
  'flex',
  'floating-labels',
  'form-check-radios',
  'form-color-pickers',
  'form-datetime-pickers',
  'form-file-uploads',
  'form-input-group',
  'form-input-masks',
  'form-inputs',
  'form-layout',
  'form-range',
  'form-select',
  'form-select2',
  'form-validation',
  'full-calendar',
  'gallery',
  'google-maps',
  'grid-tables',
  'gutters',
  'helpers',
  'icons',
  'images-figures',
  'dashboard-2',
  'dashboard-3',
  'dashboard-4',
  'dashboard-5',
  'invoice',
  'leaflet-maps',
  'listgroup',
  'mail-read',
  'mail',
  'modals-closes',
  'more',
  'navbar',
  'navs-tabs',
  'notifications',
  'object-fit',
  'offcanvas',
  'pagination',
  'placeholders',
  'popovers',
  'position',
  'pricing',
  'product-details',
  'products',
  'profile',
  'progress',
  'quill-editor',
  'ratings',
  'scrollspy',
  'search',
  'settings',
  'spinners',
  'sweet-alerts',
  'swiperjs',
  'tables',
  'terms-conditions',
  'timeline',
  'to-do-list',
  'toasts',
  'tooltips',
  'tree-view',
  'typography',
  'vector-maps',
  'widgets',
  'wishlist',
] as const

export type ShowcasePage = (typeof showcasePages)[number]

export const showcasePageSet: ReadonlySet<string> = new Set(showcasePages)

export default showcasePages
